### ISSUE TITLE
Command prompt for temperature/fan sensors.

### ISSUE THREAD

**Issue by ajasoncoleman** [ajasoncoleman/Linuxsystem#1]
Figure out the terminalology for getting your sensor array to output temperatures and fan speeds.
It's a good, practical thing to monitor, and a good place to check if things get bogged down... eliminate underlying hardware issues impacting functionality.
"Terminalology" is pretty good, I think.

When you call up the code, report back to this issue with:

--Code needed to generate output.
--Output types and options (explain as needed if information/data is not conventionally understandable).
--Output values and relevance as relates to physical machine.

**Comment by akanik** [comment]
```
Now follows a summary of the probes I have just done.
Just press ENTER to continue: 

Driver `coretemp':
  * Chip `Intel digital thermal sensor' (confidence: 9)

To load everything that is needed, add this to /etc/modules:
#----cut here----
# Chip drivers
coretemp
#----cut here----
If you have some drivers built into your kernel, the list above will
contain too many modules. Skip the appropriate ones!

Do you want to add these lines automatically to /etc/modules? (yes/NO)

Unloading i2c-i801... OK
Unloading cpuid... OK
```

**Comment by akanik** [comment]
I'm not sure exactly what all this means but:
```
alexandra@alexandra-Dell-System-Inspiron-N4110:~$ sensors
acpitz-virtual-0
Adapter: Virtual device
temp1:        +60.0°C  (crit = +100.0°C)
temp2:        +60.0°C  (crit = +100.0°C)

coretemp-isa-0000
Adapter: ISA adapter
Physical id 0:  +57.0°C  (high = +80.0°C, crit = +85.0°C)
Core 0:         +54.0°C  (high = +80.0°C, crit = +85.0°C)
Core 1:         +57.0°C  (high = +80.0°C, crit = +85.0°C)

dell_smm-virtual-0
Adapter: Virtual device
Processor Fan:    0 RPM
CPU:            +57.0°C  
Ambient:        +41.0°C  
Other:          +58.0°C  
SODIMM:         +42.0°C 
```

**Comment by ajasoncoleman** [comment]
Let me break it down!

These are THREE separate sensor arrays taking readings from your computer at all times. The virtual, coretemp and smm virtual are different versions of the same thing.

Temps 1 and 2 are (probably) sensors designed to take the temperatures of the area surrounding the processors. My guess is that there's one on the heat sink and one on the other side of the motherboard.

The "crit" temperatures are the point at which your computer will shit its pants and run away. Once the shit cools down enough for it to change its trousers it can be powered back up but routinely running around 90-100 C will cause chronic diarrhea directly into your computer's overalls.

Core 0 and 1 are as close as a sensor can get to saying what the temperatures of your actual working processor cores are. The physical ID is a representation, I believe, of the temperature output of your "virtual cores", basically representing the heat output of the added processing power.

CPU a reading from another source for the same. Ambient is the temperature of the casing generally. I'm going to take a wild guess and say that "other" is the reading from the sensor near the graphics processor--usually there's a reading for that, as it generates a lot of heat energy as it works and is very sensitive to excessive temperatures.

The SODIMM is your memory and memory controller--RAM sticks and its reader/allocator.

That's the geography of the heat-sensitive heat-generating elements in the architecture of your computer! Keep a spare pair of drawers around for it!
